# Change these first
owner: Aryaman-metadome # Your GitHub organization or username, where this repository lives
repo: test # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
    
