# Upptime configuration file
owner: Aryaman-metadome
repo: vsa-ai
# Used to display the name of your status page
siteName: "My Status Page"
# The branch where uptime commits are made
branch: master

# List of URLs to monitor
sites:
  - name: Main Website
    url: https://www.google.com
    method: GET
    maxResponseTime: 3000  # Maximum response time in ms before marking as slow
    expectedStatusCodes: [200, 201, 202] # List of expected status codes


# Interval settings (in minutes)
uptimeCheckInterval: 5  # Frequency of checks
commitMessages:
  live: ":green_circle: Site is up"
  outage: ":red_circle: Site is down"
  degraded: ":yellow_circle: Response time is high"



# Summary settings
status:
  showResponseTime: true
  days: 30

# CI/CD settings
assignees:
  - your-github-username
